default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123
  host: localhost
  port: 5432
  pool: 27
  
development:
  <<: *default
  database: lakbima_development
production:
  <<: *default
  database: lakbima_production
test:
  <<: *default
  database: lakmiba_test
