# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b771cc0b97ab6a15fe3becc38791c0e45651c4ee1e29b1c9238284b9f196aeb7f16f0d31c105afd5c49e5014c442d40fac88f61f56c31f0f32e44433e792c7

test:
  secret_key_base: b93445f406b7492420818a889ae44e828f36050d829ff8da9ddcadd6fada23ad0d2409d0be88ff3de3abb4c105f9c2e66aaa28059131cd39913be0fdb32fb9ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
